version: '3.9'

services:
  networkx:
    build: .
    image: taylorm/flanneltrack
    working_dir: /tmp
    entrypoint:
    - bash
    - -x
    - -c
    - |
      python main.py
      cat test.dot | dot -Tpng >out.png
    volumes:
    - .:/tmp
